version: '3'

services:
  api:
    build:
      context: ./..
      dockerfile: ./deploy/sportspace/Dockerfile
    container_name: sportspace-api
    restart: always
    environment:
      HTTP_ADDRESS: 0.0.0.0:8080
      BASE_URL: http://localhost:8080
      SECRET_KEY: secret_key_phrase
      LOG_LEVEL: debug
      DATABASE_URI: postgres://root:root@database:5432/sportspace?sslmode=disable
      GIN_MODE: release
      UPLOAD_PATH: /app/uploads
      UPLOAD_MAX_SIZE: 2097152 #2mb

      MAIL_SMTP_HOST: mail
      MAIL_SMTP_PORT: 1025
      MAIL_SENDER: no-report@test.ru
      MAIL_SENDER_PASSWORD: test
      MAIL_SECURE: 0
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./data/logs:/app/logs
      - ./data/uploads:/app/uploads
    networks:
      - sportspace-network

  database:
    image: postgres:13.3
    container_name: sportspace-db
    restart: always
    environment:
      POSTGRES_DB: sportspace
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/pgs-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - '5432'
    networks:
      - sportspace-network

  mail:
    image: maildev/maildev
    container_name: mail
    restart: always
    environment:
      - TZ=Asia/Omsk
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - sportspace-network

networks:
  sportspace-network:
    external: true
