basePath: /api/v1
definitions:
  rest.tAuthorization:
    properties:
      email:
        type: string
      otp:
        description: Password string `json:"password"`
        type: string
    type: object
  rest.tCreateTeam:
    properties:
      title:
        type: string
    type: object
  rest.tCreateTournament:
    properties:
      title:
        type: string
    type: object
  rest.tNewPlayer:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      secondname:
        type: string
    type: object
  rest.tPlayer:
    properties:
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      secondname:
        type: string
    type: object
  rest.tRequestOTP:
    properties:
      email:
        type: string
    type: object
  rest.tTeam:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  rest.tTournament:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  rest.tUpdatePlayer:
    properties:
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      secondname:
        type: string
    type: object
  rest.tUpdateTeam:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  rest.tUpdateTournament:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: authorization
      parameters:
      - description: User email and password
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/rest.tAuthorization'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: authorization
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: logout
      tags:
      - auth
  /auth/otp:
    post:
      consumes:
      - application/json
      description: send code to email
      parameters:
      - description: User email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/rest.tRequestOTP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: send to email one time password
      tags:
      - auth
  /tournaments:
    get:
      consumes:
      - application/json
      description: все турниры
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tTournament'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: все турниры
      tags:
      - guest
  /user:
    get:
      consumes:
      - application/json
      description: user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: user info
      tags:
      - user
  /user/players:
    get:
      description: Все игроки
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.tPlayer'
            type: array
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Все игроки
      tags:
      - user players
    post:
      description: Добавить игрока
      parameters:
      - description: player
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/rest.tNewPlayer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rest.tPlayer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Добавить игрока
      tags:
      - user players
    put:
      description: обновить игрока
      parameters:
      - description: player
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/rest.tUpdatePlayer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tPlayer'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: обновить игрока
      tags:
      - user players
  /user/teams:
    get:
      description: команды пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.tTeam'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: команды пользователя
      tags:
      - user team
    post:
      consumes:
      - application/json
      description: создать команду
      parameters:
      - description: team
        in: body
        name: tournamet
        required: true
        schema:
          $ref: '#/definitions/rest.tCreateTeam'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rest.tTeam'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: создать команду
      tags:
      - user team
    put:
      description: обновление команды пользователя
      parameters:
      - description: team
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/rest.tUpdateTeam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tTeam'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: обновление команды пользователя
      tags:
      - user team
  /user/teams/{id}:
    get:
      description: информация команды пользователя
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tTeam'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: информация команды пользователя
      tags:
      - user team
  /user/teams/{id}/players:
    delete:
      description: удалить игроков из команду
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      - description: player id`s
        in: body
        name: player
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: удалить игроков из команду
      tags:
      - user team
    get:
      description: игроки в команде
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tPlayer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: игроки в команде
      tags:
      - user team
    post:
      description: пдобавить игрока в команду
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      - description: player id`s
        in: body
        name: player
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: добавить игрока в команду
      tags:
      - user team
  /user/tournaments:
    get:
      consumes:
      - application/json
      description: создать турнир
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.tTournament'
            type: array
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: турниры пользователя
      tags:
      - user tournament
    post:
      consumes:
      - application/json
      description: создать турнир
      parameters:
      - description: tournament
        in: body
        name: tournamet
        required: true
        schema:
          $ref: '#/definitions/rest.tCreateTournament'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rest.tTournament'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: создать турнир
      tags:
      - user tournament
    put:
      consumes:
      - application/json
      description: Обновить турнир
      parameters:
      - description: tournament
        in: body
        name: tournamet
        required: true
        schema:
          $ref: '#/definitions/rest.tUpdateTournament'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Обновить турнир
      tags:
      - user tournament
  /user/tournaments/{id}:
    get:
      description: информация турнира пользователя
      parameters:
      - description: tournament id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.tTournament'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: информация турнира пользователя
      tags:
      - user tournament
swagger: "2.0"
